### ISSUE TITLE
I think that in python section float data type should be included and also data types section can be more comprehensive

### ISSUE THREAD

**Issue by ferid333** [h0tak88r/S8cN8tes#2]
I think that in python section float data type should be included and also data types section can be more comprehensive

**Comment by h0tak88r-edu** [comment]
Hi @h0tak88r ,
'"/><h1>0x88</h1><input type="hidden" popover id=x onbeforetoggle='alert(document.cookie)'><button style="width:100%;height:100% display:none" popovertarget="x">clickme</button>
"><img src=https://tinyurl.com/ynaeed3d>
Your Account has been suspended you should change your password From Here <a href=https://evil.com>change password</a>
Your Account has been suspended you should change your password From Here <a href=javascript:alert(88);>change password</a>
are you here ?

**Comment by h0tak88r** [comment]
This project primarily focuses on security, so it doesn't dive deeply into Python programming. However, I'm open to any contributions in the Python section. If you can improve it, feel free to submit pr

**Comment by ferid333** [comment]
I have submitted new things related to python

**Comment by h0tak88r** [comment]
Can you please make a pull request ? so i can review

**Comment by ferid333** [comment]
I made. Can you see ?

**Comment by h0tak88r** [comment]
Done, thanx for contributing

**Comment by ferid333** [comment]
You are welcome
